// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(FarmContext))]
    [Migration("20240918185839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Livestock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("MilkProduced")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Offspring")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Livestock", (string)null);

                    b.HasDiscriminator<string>("LivestockType").HasValue("Livestock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DAL.Cow", b =>
                {
                    b.HasBaseType("DAL.Livestock");

                    b.HasDiscriminator().HasValue("1");
                });

            modelBuilder.Entity("DAL.Goat", b =>
                {
                    b.HasBaseType("DAL.Livestock");

                    b.HasDiscriminator().HasValue("2");
                });

            modelBuilder.Entity("DAL.Sheep", b =>
                {
                    b.HasBaseType("DAL.Livestock");

                    b.HasDiscriminator().HasValue("3");
                });
#pragma warning restore 612, 618
        }
    }
}
